<a href="https://colab.research.google.com/github/maya-papaya/ads1-cervical-cancer-analysis/blob/main/Creating%20Relational%20Database%20(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Relational Database

https://tableplus.com/blog/2018/04/sqlite-specify-primary-key-on-multiple-columns.html#:~:text=How%20to%20specify%20primary%20key,KEY%20(column1%2C%20column2)%20)%3B

Primary key:
Identifies a single row within a table uniquely.
Cannot have duplicate values.
Usually a single column, but can be a combination of columns (composite key).

Foreign key:
A column in one table that references the primary key of another table.
Ensures that the values in a foreign key column exist in the referenced primary key column.
Used to create relationships between tables

In [1]:
# SETTING UP COLAB AND MODULES
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

import os
os.chdir("/content/drive/My Drive/ADS_Maya_Reddy/projects/disease_project_1/prepped_datasets/")

Mounted at /content/drive

In [2]:
# LOADING DATASETS
data = pd.read_csv('data.csv')
pap = pd.read_csv('pap.csv')
hpv = pd.read_csv('hpv.csv')
screening_program = pd.read_csv('screening_program.csv')
medicaid_chip = pd.read_csv('medicaid_chip.csv')
adolescent = pd.read_csv('adolescent.csv')

In [10]:
# CREATING DATABASE TABLES
import sqlite3
connection = sqlite3.connect('cervical_cancer.db')
cursor = connection.cursor()

# CREATE THE 'data' TABLE
cursor.execute('''
CREATE TABLE IF NOT EXISTS data (
    measure TEXT NOT NULL,
    location TEXT NOT NULL,
    metric TEXT NOT NULL,
    year INTEGER NOT NULL,
    val FLOAT NOT NULL,
    upper FLOAT NOT NULL,
    lower FLOAT NOT NULL
)''')
# SOURCED FROM https://theleftjoin.com/how-to-write-a-pandas-dataframe-to-an-sqlite-table/
data.to_sql('data', connection, if_exists='replace', index=False)

# CREATE THE 'pap' TABLE
cursor.execute('''
CREATE TABLE IF NOT EXISTS pap (
    state TEXT NOT NULL,
    city TEXT NOT NULL,
    pop_2010, INTEGER NOT NULL,
    val FLOAT NOT NULL,
    lower FLOAT NOT NULL,
    upper FLOAT NOT NULL,
    year INTEGER NOT NULL
)
''')
pap.to_sql('pap', connection, if_exists='replace', index=False)

# Create the 'hpv' table
cursor.execute('''
CREATE TABLE IF NOT EXISTS hpv (
    cohort_size FLOAT NOT NULL,
    current_cov FLOAT NOT NULL,
    curr_vacc_cohort_size FLOAT NOT NULL,
    future_cov FLOAT NOT NULL,
    future_vacc_cohort_size FLOAT NOT NULL,
    curr_cc_prev FLOAT NOT NULL,
    curr_mort_prev FLOAT NOT NULL,
    curr_cost FLOAT NOT NULL,
    curr_cost_prev FLOAT NOT NULL,
    proj_cc_prev FLOAT NOT NULL,
    proj_mort_prev FLOAT NOT NULL,
    proj_cost FLOAT NOT NULL,
    year INTEGER NOT NULL,
    current_net_cost FLOAT NOT NULL,
    country TEXT NOT NULL
)
''')
hpv.to_sql('hpv', connection, if_exists='replace', index=False)

# Create the 'screening_programs' table
cursor.execute('''
CREATE TABLE IF NOT EXISTS screening_programs (
    country TEXT NOT NULL,
    code INTEGER NOT NULL,
    year INTEGER NOT NULL,
    screening_program TEXT NOT NULL
)
''')
screening_program.to_sql('screening_programs', connection, if_exists='replace', index=False)

# Create the 'medicaid_chip' table
cursor.execute('''
CREATE TABLE IF NOT EXISTS medicaid_chip (
    state TEXT NOT NULL,
    month TEXT NOT NULL,
    year INTEGER NOT NULL,
    service_count FLOAT NOT NULL,
    rate_per_1000 FLOAT NOT NULL
)
''')
medicaid_chip.to_sql('medicaid_chip', connection, if_exists='replace', index=False)

# Create the 'adolescent' table
cursor.execute('''
CREATE TABLE IF NOT EXISTS adolescent (
    location TEXT NOT NULL,
    location_type TEXT NOT NULL,
    year TEXT NOT NULL,
    dose TEXT NOT NULL,
    dimension_type TEXT NOT NULL,
    dimension_val TEXT NOT NULL,
    val FLOAT NOT NULL,
    sample_size FLOAT NOT NULL,
    lower FLOAT NOT NULL,
    upper FLOAT NOT NULL
)
''')
adolescent.to_sql('adolescent', connection, if_exists='replace', index=False)

# Commit the changes to the database
connection.commit()

In [12]:
# CHECKING DATABASE TABLES
pd.read_sql('SELECT * FROM data', connection)

,measure,location,metric,year,val,upper,lower
0,Deaths,Massachusetts,Number,1980,156.027002,167.409189,144.935259
1,Deaths,Massachusetts,Rate,1980,5.121602,5.495223,4.757514
2,Deaths,Oregon,Number,1980,57.602448,62.026101,52.861243
3,Deaths,Oregon,Rate,1980,4.256527,4.583412,3.906176
4,Deaths,Michigan,Number,1980,229.941567,244.664251,214.484653
...,...,...,...,...,...,...,...
7543,Incidence,Virginia,Rate,2019,14.378934,15.608259,13.251705
7544,Incidence,Virginia,Number,2020,635.334743,710.285851,571.862097
7545,Incidence,Virginia,Rate,2020,14.460380,16.166286,13.015726
7546,Incidence,Virginia,Number,2021,639.128842,811.775169,507.834033
7547,Incidence,Virginia,Rate,2021,14.503574,18.421390,11.524137